version: '3.8'

services:
  web:
    build: .
    command: gunicorn biblioteca.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE=biblioteca.settings
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=acervo.easistemas.dev.br
      - POSTGRES_DB=biblioteca
      - POSTGRES_USER=biblioteca_user
      - POSTGRES_PASSWORD=Fep09151@
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=biblioteca
      - POSTGRES_USER=biblioteca_user
      - POSTGRES_PASSWORD=Fep09151@

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: 