services:
  web:
    build: .
    command: gunicorn biblioteca.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8080:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=biblioteca.settings
      - DJANGO_SECRET_KEY=hx_hdn@-@#0whm51+8#9$@w^%8e1-@6cgr937mz*+^i%rqox^a
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=acervo.easistemas.dev.br
      - POSTGRES_DB=acervolight
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Fep09151@
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Fep09151@
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  static_volume:
    driver: local
    driver_opts:
      type: none
      device: /var/www/acervolight/static
      o: bind
  media_volume:
    driver: local
    driver_opts:
      type: none
      device: /var/www/acervolight/media
      o: bind 