# Generated by Django 5.2 on 2025-04-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secao',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='secao',
            name='descricao',
        ),
        migrations.AddField(
            model_name='secao',
            name='nome',
            field=models.CharField(default=None, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
