# Generated by Django 5.2 on 2025-04-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacao', '0002_remove_secao_codigo_remove_secao_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdd',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='cdu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='cutter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cdd',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cdu',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cutter',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
