# Generated by Django 5.2 on 2025-04-14 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacao', '0003_cdd_id_cdu_id_cutter_id_alter_cdd_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('ano_publicacao', models.IntegerField()),
                ('editora', models.CharField(max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cdd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='importacao.cdd')),
                ('cdu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='importacao.cdu')),
                ('cutter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='importacao.cutter')),
                ('secao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='importacao.secao')),
            ],
        ),
    ]
