# Generated by Django 5.2 on 2025-04-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacao', '0004_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inep_aluno', models.BigIntegerField(blank=True, null=True, verbose_name='Código INEP')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('dt_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('nis', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIS')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Gênero')),
                ('raca', models.CharField(blank=True, choices=[('Branca', 'Branca'), ('Preta', 'Preta'), ('Parda', 'Parda'), ('Amarela', 'Amarela'), ('Indígena', 'Indígena'), ('Não declarada', 'Não declarada')], max_length=15, null=True, verbose_name='Raça/Cor')),
                ('inep_escola', models.BigIntegerField(blank=True, null=True, verbose_name='Código INEP da Escola')),
                ('turma', models.CharField(blank=True, max_length=50, null=True, verbose_name='Turma')),
                ('serie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Série')),
                ('ano', models.IntegerField(blank=True, null=True, verbose_name='Ano Letivo')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('nome_mae', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Mãe')),
                ('nome_responsavel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
    ]
